--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Frost-Creations/FrostMaintenanceMode
build-by-default: true
branches:
- main
projects:
  FrostMaintenanceMode:
    path: ""
    icon: ""
...
